"""unificar en una sola tabla

Revision ID: 27cb6c37d3f2
Revises: 3a2cd332113a
Create Date: 2026-01-14 22:15:21.713209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27cb6c37d3f2'
down_revision = '3a2cd332113a'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deudas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('socio_cuit_idx'))

    op.drop_table('deudas')
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_adeudado', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_table_comment(
        existing_comment='\t\t\t'
    )

    # ### end Alembic commands ###


def downgrade():
   
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.create_table_comment(
        '\t\t\t',
        existing_comment=None
    )
        batch_op.drop_column('monto_adeudado')

    op.create_table('deudas',
    sa.Column('idpagos_cuota', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monto_adeudado', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('socio_cuit', mysql.VARCHAR(length=14), nullable=True),
    sa.ForeignKeyConstraint(['socio_cuit'], ['socio.cuit'], name=op.f('socio_cuit')),
    sa.PrimaryKeyConstraint('idpagos_cuota'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('deudas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('socio_cuit_idx'), ['socio_cuit'], unique=False)



    # ### end Alembic commands ###
