"""Inicializando base de datos en Railway

Revision ID: 3a2cd332113a
Revises: 
Create Date: 2026-01-04 21:54:36.099255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2cd332113a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socio',
    sa.Column('cuit', sa.String(length=14), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('cuit'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('deudas',
    sa.Column('idpagos_cuota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monto_adeudado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('socio_cuit', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['socio_cuit'], ['socio.cuit'], ),
    sa.PrimaryKeyConstraint('idpagos_cuota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deudas')
    op.drop_table('socio')
    # ### end Alembic commands ###
