"""queda una sola tabla en server

Revision ID: 3c359fbf06e1
Revises: a536f94a5f62
Create Date: 2026-01-15 01:10:50.189950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c359fbf06e1'
down_revision = 'a536f94a5f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_adeudado', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('monto_adeudado')

    # ### end Alembic commands ###
