"""unificar en una sola tabla 2

Revision ID: a536f94a5f62
Revises: 27cb6c37d3f2
Create Date: 2026-01-14 22:19:17.557901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a536f94a5f62'
down_revision = '27cb6c37d3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_adeudado', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_table_comment(
        existing_comment='\t\t\t'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.create_table_comment(
        '\t\t\t',
        existing_comment=None
    )
        batch_op.drop_column('monto_adeudado')

    # ### end Alembic commands ###
